#!/bin/bash

domain=$1

if [ -z "$domain" ]; then
    echo "Usage: crtsh domain.com"
    exit 1
fi

curl -s "https://crt.sh/?q=%25.$domain&output=json" \
| jq -r '.[].name_value' \
| sed 's/\*\.//g' \
| sort -u
